### ISSUE TITLE
The game was very surprising

### ISSUE THREAD

**Issue by Curtaingit** [wheybags/DungeonsAndDirectories#3]
Three years later, there is no sequel.
 expecting.

**Comment by wheybags** [comment]
Yup, sorry. I am working on (and about to release) a different game though:
https://store.steampowered.com/app/2338630/Drilbert/

**Comment by wheybags** [comment]
You made a [Chinese translation](https://github.com/Curtaingit/DungeonsAndDirectories)! That's awesome. If you add some way to have both languages in the same codebase, I'd be happy to pull that into upstream
